FROM mongo:latest

COPY init-db.js /docker-entrypoint-initdb.d/

#Install node
# RUN apt-get update && apt-get install -y nodejs

# Create a custom entry point script
# COPY entrypoint.sh /entrypoint.sh
# RUN chmod +x /entrypoint.sh

EXPOSE 27017

# Start MongoDB
CMD ["mongod"]