version: '3'

services:
  mongodb:
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Dice_Game
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - mynetwork

  spring-app:
    #restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    build:
      context: .
      dockerfile: Dockerfile.application
    container_name: spring-app
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: mynetwork