version: '3'

services:
  mongodb:
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Dice_Game
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    #volumes:
      #- ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - mynetwork

  spring-app:
    #restart: always
    environment:
        SPRING_DATA_MONGODB_HOST: mongodb
        SPRING_DATA_MONGODB_PORT: 27017
        SPRING_DATA_MONGODB_DATABASE: Dice_Game
        SPRING_DATA_MONGODB_USERNAME: normalUser
        SPRING_DATA_MONGODB_PASSWORD: password

    build:
      context: .
      dockerfile: Dockerfile.myapp
    container_name: spring-app
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
    # driver_opts:
      # com.docker.network.bridge.name: mynetwork