spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      # host: mongodb
      # port: 27017
      uri: mongodb://mongodb:27017/Dice_Game
server:
  port: 8081
